name: GitHub Actions Rate-Limit Reporter
description: GitHub Action used to report on current rate-limit data as part of an Actions workflow
author: 'Collin McNeese'
branding:
  icon: 'bar-chart'
  color: 'blue'
inputs:
  render:
    description: 'Optional. Whether or not to render the data as a table. Defaults to true.'
    default: "true"
    required: true
  access-token:
    description: 'The GitHub access token to use for the request.'
    required: true
outputs:
  rateLimitObject:
    description: 'The raw rate-limit object returned from the GitHub API.'
runs:
  using: node24
  main: 'dist/index.cjs'
